### ISSUE TITLE
Use WebSockets for asynchronous API calls

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-api-gtw#143]
Agreed with @antonroman (CC @anapolg ):

- [ ] return `202 Accepted`, with the token in a header (`X-User-Token`?);
- [ ] `POST` any change into a `ws://...`

@antonroman: what's the template for this URL, does it has a Portal-related URL? how does the GK know that? Maybe the Portal could send (part of) that URL (without the token) in that `callback` field?

**Comment by anapolg** [comment]
![wss](https://user-images.githubusercontent.com/35800470/47201765-44973b00-d37b-11e8-91c3-f4c00dcaac67.png)

**Comment by jbonnet** [comment]
We're not going to implement this, given lack of time.
