### ISSUE TITLE
Add user name and email to get endpoints

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-api-gtw#180]
Specificaly, these ones:

1. GET http://localhost:8080/tng-sla-mgmt/api/slas/v1/agreements/customer
1. GET http://localhost:8080/tng-sla-mgmt/api/slas/v1/licenses/status/{sla_uuid}/{ns_uuid}

**Comment by jbonnet** [comment]
@ekapassa @mtouloup Can you please test this? Implemented via PR #181

**Comment by mtouloup** [comment]
Hi @jbonnet ,

After some minor updates to the SLA manager side, both end points work like a charm! You can close the issue. 

Thanks for the effort,
Marios

**Comment by jbonnet** [comment]
Top! 👍
