### ISSUE TITLE
Add a route for PUT a change in a test plan

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-api-gtw#206]
The V&V route to PUT a change in the status of a test plan (and like this execute it manually) is:
http://pre-int-vnv-bcn.5gtango.eu:6100/swagger-ui.html#/test-plan-controller/updateUsingPUT

or what is the same: 
PUT `/api/v1/test-plans/{uuid}`

Portal needs a route to /test-plans (already provided with `/tests/plans`) that supports PUT method.

**Comment by anapolg** [comment]
Example from Swagger exposed endpoints 
`curl -X PUT "http://pre-int-vnv-bcn.5gtango.eu:6100/api/v1/test-plans/906ffd65-838d-4dd9-b552-8756525e7e8a?status=SCHEDULED" -H "accept: */*"`

**Comment by jbonnet** [comment]
Closed via #209
