### ISSUE TITLE
Add a route for the creation of test plans from a test uuid

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-api-gtw#207]
The V&V route to POST a group of test plans related to a test UUID is:
http://pre-int-vnv-bcn.5gtango.eu:6100/swagger-ui.html#/test-plan-controller/buildTestPlansByTestUsingPOST

POST /api/v1/test-plans/tests

Portal needs a route to /test-plans/tests that supports POST method.

Example from Swagger:
curl -X POST "http://pre-int-vnv-bcn.5gtango.eu:6100/api/v1/test-plans/tests?confirmRequired=true&testUuid=526bb462-736f-44ff-9ca3-ee393ca71567" -H "accept: */*"

**Comment by jbonnet** [comment]
Closed by #209.
@srodriguezOPT I think you need to configure the Planner's response in order to avoid the 'chunked' response:
```sh
$ curl -X POST "http://pre-int-vnv-bcn.5gtango.eu:32002/api/v3/tests/plans/tests?confirmationRequired=true&testUuid=526bb462-736f-44ff-9ca3-ee393ca71567" -H 'content-type:application/json'
curl: (56) Illegal or missing hexadecimal sequence in chunked-encoding
```
