### ISSUE TITLE
[VnV standalone stucked between tng-api-gtw and tng-vnv-planner]

### ISSUE THREAD

**Issue by sinaure** [sonata-nfv/tng-api-gtw#228]
Test plan stucked between planner and gatekeeper
![Capture](https://user-images.githubusercontent.com/16242967/69344320-7f9b2a80-0c6f-11ea-8fb2-d483070eba78.PNG)

**Comment by jbonnet** [comment]
@sinaure do you have any request for validation in the teste descriptor?
CC @anapol

**Comment by anapolg** [comment]
Hi, how did you launch the test @sinaure :
1. with Portal?
2. from the view of the already existing test plans? from the one of the tests list through a dialog asking you if you want to confirm execution or not?

**Comment by sinaure** [comment]
First I've runned it manually using 'robot test.robot'
Then I've retriggered the already existing one from portal dialog

**Comment by sinaure** [comment]
https://github.com/sonata-nfv/tng-api-gtw/blob/master/tng-sec-gtw/README.md
I think during the ansible build is not overriding routes.yml

**Comment by jbonnet** [comment]
@sinaure Have you got this solved?
