### ISSUE TITLE
Integrate with the Slice Manager

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-api-gtw#56]
To create an NST do this:
```shell
curl -i -H "Content-Type:application/json" -X POST -d'{"name":"Rubik_NST", "version":"<version_number>", "author":"<author_name>", "vendor":"<vendor_name>", "nstNsdIds":[{"NsdId":"<network_service_ID>"}]}' pre-int-sp-ath.5gtango.eu:32002/api/nst/v1/descriptors
```

Valid NST example:
```json
{
  "designer": "Pol",
  "id": "30ef541d-24ee-4ec3-8c00-f53b4a3791cb",
  "name": "Rubik_NST",
  "notificationTypes": "",
  "nstNsdIds": [
    "6a01afdc-9d42-4bc9-866c-a8a3868fdf5e"
  ],
  "onboardingState": "ENABLED",
  "operationalState": "ENABLED",
  "usageState": "NOT_IN_USE",
  "userDefinedData": "",
  "vendor": "5gTango",
  "version": "1.0"
}
```

**Comment by alemanyp** [comment]
Thats a Valid NST example:

{
    "created_at": "2018-06-28T07:43:23.858+00:00",
    "md5": "dda2a38d73c65652de4f2103bf64fb09",
    "nstd": {
      "author": "Pol Alemany, CTTC",
      "name": "Example_NST",
      "notificationTypes": "",
      "nstNsdIds": [
        "52e3ae6f-8280-4a76-998c-21138dad9867"
      ],
      "onboardingState": "ENABLED",
      "operationalState": "ENABLED",
      "usageState": "IN_USE",
      "userDefinedData": "",
      "vendor": "eu.5gTango",
      "version": "1.0"
    },
    "signature": null,
    "status": "active",
    "updated_at": "2018-06-28T08:03:08.088+00:00",
    "username": null,
    "uuid": "67ca5d38-2193-4e63-8099-9009390e1145"
  }

**Comment by jbonnet** [comment]
This has been implemented
